#include <iostream>
using namespace std;
int main()
{
    int gift5;
    cout << "Enter the number of Gift/5 boxes = ";
    cin >> gift5;
    int gift4;
    cout << "Enter the number of Gift/4 boxes = ";
    cin >> gift4;
    int gift5r;
    cout << "Enter the number of Gift/5 roll boxes = ";
    cin >> gift5r;
    int gift5x;
    cout << "Enter the number of 5x/5 boxes = ";
    cin >> gift5x;
    int gift4x;
    cout << "Enter the number of 5x/4 boxes = ";
    cin >> gift4x;
    int sum_boxes = gift5 + gift4 + gift5r + gift5x + gift4x;
    cout << "\n";
    int rate5;
    cout << "Enter the rate of one Gift/5 box = ";
    cin >> rate5;
    int total_amount5 = rate5 * gift5;
    int rate4;
    cout << "Enter the rate of one Gift/4 box = ";
    cin >> rate4;
    int total_amount4 = rate4 * gift4;
    int rate5r;
    cout << "Enter the rate of one Gift/5 Roll box = ";
    cin >> rate5r;
    int total_amount5r = rate5r * gift5r;
    int rate5x;
    cout << "Enter the rate of one 5x/5 box = ";
    cin >> rate5x;
    int total_amount5x = rate5x * gift5x;
    int rate4x;
    cout << "Enter the rate of one 5x/4 box = ";
    cin >> rate4x;
    int total_amount4x = rate4x * gift4x;
    int total_amount = total_amount5 + total_amount4 + total_amount5r + total_amount5x + total_amount4x;
    cout << "\n";
    int cost;
    cout << "Enter the cost of one cardboard / wooden box = ";
    cin >> cost;
    int totalcost_boxes = sum_boxes * cost;
    cout << "\n";
    int ft;
    cout << "Enter the commission persentage of Fruit Trader = ";
    cin >> ft;
    int commission = total_amount * (ft / 100.0);
    cout << "\n";
    int freight;
    cout << "Enter the Freight of one box = ";
    cin >> freight;
    int total_freight = sum_boxes * freight;
    cout << "\n";
    cout << "Total number of boxes = " << sum_boxes;
    cout << "\n";
    cout << "Total amount =  " << total_amount;
    cout << "\n";
    cout << "Total commission of fruit trader = " << commission;
    cout << "\n";
    cout << "Total freight = " << total_freight;
    cout << "\n";
    cout << "Total cost of cardboard / wooden boxes = " << totalcost_boxes;
    cout << "\n";
    cout << "In Hand amount to the Grower =  " << total_amount - (commission + total_freight + totalcost_boxes);
    cout << "\n";
    return 0;
}
